#syntax =docker/dockerfile:1
#escape=\
# This here is a comment \
  comment after line continuation
   # another comment with to many spaces

#invalidDirective=duplicateDirective
FROM ubuntu:18.04
RUN echo "Hello World" \
# here is a comment
    echo "test"
